# Nonlinear System Parameters
model_params:
  n_states: 3
  n_inputs: 1
  l_f: .5 
  l_r: .5
  v: 1
  
# Linearization Parameters (Sample values, make up as needed)
mpc_params:
  dt: 0.2
  b: 0.2
  c: 0.3
  d: 0.4