# Nonlinear System Parameters
model_params:
  n_states: 3
  n_inputs: 1
  n_outputs: 3
  l_f: .8 
  l_r: .2
  v: 1
  
# Linearization Parameters (Sample values, make up as needed)
mpc_params:
  dt: 0.4 # Discretization time step
  b: 0.2
  c: 0.3
  d: 0.4