# Nonlinear System Parameters
model_params:
  n_states: 4
  n_inputs: 2
  n_outputs: 3
  l_f: 2.3
  l_r: 0.1
  v: 1
  
# Linearization Parameters (Sample values, make up as needed)
mpc_params:
  dt: .1
  b: 0.2
  c: 0.3
  d: 0.4